### ISSUE TITLE
undefined/undefined crash

### ISSUE THREAD

**Issue by JimBobSD** [sibartlett/homebridge-wink3#10]
One more crash:

[5/17/2017, 10:11:33 PM] [Wink] Sending update: Backdoor Deadbolt (lock/151114) { locked: true }
[5/17/2017, 10:11:34 PM] [Wink] Update sent successfully: Backdoor Deadbolt (lock/151114)
[5/17/2017, 10:11:34 PM] [Wink] Received update notification: Backdoor Deadbolt (lock/151114)
[5/17/2017, 10:11:40 PM] [Wink] Received update notification: Backdoor Deadbolt (lock/151114)
[5/17/2017, 10:42:02 PM] [Wink] Received update notification: Backdoor Deadbolt (undefined/undefined)

/usr/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:124
    const context = accessory.context;
                    ^
TypeError: Cannot read property 'context' of undefined
    at AccessoryHelper.updateAccessoryState (/usr/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:124:21)
    at WinkPlatform.updateDevice (/usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:119:26)
    at Subscriptions.WinkPlatform.subscriptions.on.device (/usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:38:12)
    at emitOne (events.js:96:13)
    at Subscriptions.emit (events.js:191:7)
    at Subscriptions.onMessage (/usr/lib/node_modules/homebridge-wink3/src/Subscriptions.js:46:12)
    at /usr/lib/node_modules/homebridge-wink3/node_modules/pubnub/lib/core/components/core/components/listener_manager.js:45:38
    at Array.forEach (native)
    at _class.announceMessage (/usr/lib/node_modules/homebridge-wink3/node_modules/pubnub/lib/core/components/core/components/listener_manager.js:44:21)
    at /usr/lib/node_modules/homebridge-wink3/node_modules/pubnub/lib/core/components/core/components/subscription_manager.js:404:31
    at Array.forEach (native)
    at _class._processSubscribeResponse (/usr/lib/node_modules/homebridge-wink3/node_modules/pubnub/lib/core/components/core/components/subscription_manager.js:336:14)
    at onResponse (/usr/lib/node_modules/homebridge-wink3/node_modules/pubnub/lib/core/components/core/components/endpoint.js:131:7)
    at /usr/lib/node_modules/homebridge-wink3/node_modules/pubnub/lib/networking/modules/networking/modules/web-node.js:63:16
    at Request.callback (/usr/lib/node_modules/homebridge-wink3/node_modules/superagent/lib/node/index.js:619:12)
    at Stream.<anonymous> (/usr/lib/node_modules/homebridge-wink3/node_modules/superagent/lib/node/index.js:795:18)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:188:7)
    at Unzip.<anonymous> (/usr/lib/node_modules/homebridge-wink3/node_modules/superagent/lib/node/utils.js:112:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)

**Comment by sibartlett** [comment]
I've published a new version `1.1.7` which should address this. The plugin will also log unrecognized push notifications.
