### ISSUE TITLE
Strange crashing issue happening on Rpi 4 with Buster/Homebridge/HB-Wink3

### ISSUE THREAD

**Issue by themick4u** [sibartlett/homebridge-wink3#125]
I've been a user of homebridge for some time now and have just implemented a new Rpi 4 with fresh installation and when my Rpi reboots, my wink crashes out with the below debug. Wondering if anyone can point me in a direction to look as to why this might be happening. Thanks in advance

RPI 4, Buster OS
Node 10.17.0
Npm 6.12.0

[10/30/2019, 9:26:13 AM] [Wink] Refreshing devices...
[10/30/2019, 9:26:13 AM] [Wink] Failed to refresh devices. { RequestError: Error: getaddrinfo EAI_AGAIN api.wink.com api.wink.com:443
    at new RequestError (/usr/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-wink3/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-wink3/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
  name: 'RequestError',
  message: 'Error: getaddrinfo EAI_AGAIN api.wink.com api.wink.com:443',
  cause:
   { Error: getaddrinfo EAI_AGAIN api.wink.com api.wink.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'api.wink.com',
     host: 'api.wink.com',
     port: 443 },
  error:
   { Error: getaddrinfo EAI_AGAIN api.wink.com api.wink.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'api.wink.com',
     host: 'api.wink.com',
     port: 443 },
  options:
   { baseUrl: 'https://api.wink.com',
     strictSSL: true,
     json: true,
     method: 'GET',
     uri: '/users/me',
     headers:
      { 'User-Agent': 'xxxxxxxx',
        Authorization: 'Bearer xxxxxxxxx' },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

**Comment by themick4u** [comment]
[Homebridge] [11/19/2019, 12:18:32 PM] [Wink] Hub is reachable locally (Wink Hub 2, 192.168.1.74)
[Homebridge] [11/19/2019, 12:18:32 PM] [Wink] Could not authenticate with local hub (Wink Hub 2, 192.168.1.74) StatusCodeError: 400 - {"data":{"error":"invalid_grant","error_description":""},"errors":["invalid_grant: "],"pagination":{},"error":"invalid_grant","error_description":""}
[Homebridge] at new StatusCodeError (/home/homebridge/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
[Homebridge] at Request.plumbing.callback (/home/homebridge/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
[Homebridge] at Request.RP$callback [as _callback] (/home/homebridge/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
[Homebridge] at Request.self.callback (/home/homebridge/.hoobs/node_modules/request/request.js:185:22)
[Homebridge] at Request.emit (events.js:210:5)
[Homebridge] at Request.<anonymous> (/home/homebridge/.hoobs/node_modules/request/request.js:1161:10)
[Homebridge] at Request.emit (events.js:210:5)
[Homebridge] at IncomingMessage.<anonymous>

**Comment by sibartlett** [comment]
Sorry, I am no longer actively maintaining this project. I am no longer using Wink, and do not have the time or resources to dedicate more to ongoing maintenance.
