### ISSUE TITLE
Failed to refresh devices

### ISSUE THREAD

**Issue by sb13054** [sibartlett/homebridge-wink3#19]
I have installed homebridge-wink3.  When launching home bridge, I get an error about 'refresh devices'; although I'm successfully able to pair home bridge to iOS

Also, other than Jiya's Fan and Garage Entry Door, none of the devices identified below should come up.  They are not in my wink app (at one point they used to be)

Finally, I have 11 shades that are connected to wink but they are not showing up.  I have also included my config file below

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/14/2017, 9:21:26 PM] Loaded plugin: homebridge-wink3
[6/14/2017, 9:21:26 PM] Registering platform 'homebridge-wink.Wink'
[6/14/2017, 9:21:26 PM] ---
[6/14/2017, 9:21:26 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/14/2017, 9:21:26 PM] ---
[6/14/2017, 9:21:26 PM] Loading 1 platforms...
[6/14/2017, 9:21:26 PM] [Wink] Initializing Wink platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[6/14/2017, 9:21:26 PM] Homebridge is running on port 51826.
[6/14/2017, 9:21:26 PM] [Wink] Refreshing devices...
[6/14/2017, 9:21:28 PM] [Wink] Added: Sunroom Right (camera/94076)
[6/14/2017, 9:21:28 PM] [Wink] Added: Sunroom Left (camera/94077)
[6/14/2017, 9:21:28 PM] [Wink] Added: Walkout Basement (camera/95307)
[6/14/2017, 9:21:28 PM] [Wink] Added: Driveway (camera/109695)
[6/14/2017, 9:21:28 PM] [Wink] Added: Family Room Lightstrip (light_bulb/2255272)
[6/14/2017, 9:21:28 PM] [Wink] Added: Dining Lightstrip (light_bulb/2255412)
[6/14/2017, 9:21:28 PM] [Wink] Added: Kitchen (light_bulb/2275830)
[6/14/2017, 9:21:28 PM] [Wink] Added: Jiya's Fan (light_bulb/2364908)
[6/14/2017, 9:21:28 PM] [Wink] Added: Mandir (light_bulb/2695793)
[6/14/2017, 9:21:28 PM] [Wink] Added: Shadow Box (light_bulb/2695794)
[6/14/2017, 9:21:28 PM] [Wink] Added: Garage Entry Door (lock/153554)
[6/14/2017, 9:21:28 PM] [Wink] Failed to refresh devices. TypeError: Cannot read property 'setValue' of undefined
    at Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:148:31)
    at definition.characteristics.forEach.c (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:67:19)
    at Array.forEach (native)
    at services.forEach.definition (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:65:34)
    at Array.forEach (native)
    at AccessoryHelper.configureAccessoryCharacteristics (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:62:14)
    at AccessoryHelper.configureAccessory (/usr/local/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:43:10)
    at WinkPlatform.addDevice (/usr/local/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:144:26)
    at Array.forEach (native)
    at /usr/local/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:181:13
[6/14/2017, 9:21:29 PM] [Wink] Authenticated with local Wink hub (192.168.1.207)

CONFIG FILE
{
    "bridge": {
            "name": "Homebridge",
            "username": "CC:22:3D:E3:CE:30",
            "port": 51826,
            "pin": "031-45-154"
    },

  "platforms": [
    {
      "platform": "Wink",
      "name": "Wink",
      "username": "XXXXXXXX@gmail.com",
      "password": "XXXXX",
      "client_id": "XXXXXX",
      "client_secret": "XXXXXXXXX",
      "hide_groups": [
        "garage_door",
        "thermostat",
        "sensor_pods"
      ],
      "hide_ids": [],
      "fan_ids": [],
      "direct_access": true,
      "access_token": "XXXXXXXXX",
      "refresh_token": "XXXXXXXXX"
    }
  ]
}

**Comment by sibartlett** [comment]
I just released a new version, `1.4.4`, can you try it?

**Comment by sibartlett** [comment]
Actually, I've pushed yet another version, `1.4.5.` - which should fix both issues you raised.

**Comment by sibartlett** [comment]
Gah! There was a typo - my bad :(

I've publishde another version: `1.4.6`

**Comment by sibartlett** [comment]
I've pushed another update, `1.4.7`, this time shades should operate correctly. Sorry for all these issues! Seems like you're the first person to try and use shades with homebridge-wink3.

**Comment by JOyo246** [comment]
@sb13054 What brand/model of shades do you have and do they work well with HomeKit/Bridge?
