### ISSUE TITLE
1.6.0 Cannot read property 'services' of undefined

### ISSUE THREAD

**Issue by vraicovi** [sibartlett/homebridge-wink3#60]
Updated to 1.6.0 and get this after all the devices load from cache:

>  C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-wink3\src\AccessoryHelper.js:26
>       services: definition.services
>                 ^
> TypeError: Cannot read property 'services' of undefined
>     at AccessoryHelper.getDefinition (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-wink3\src\AccessoryHelper.js:26:17)
>     at WinkPlatform.patchAccessory (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-wink3\src\WinkPlatform.js:116:49)
>     at WinkPlatform.configureAccessory (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-wink3\src\WinkPlatform.js:104:10)
>     at Server._configCachedPlatformAccessories (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:342:24)
>     at Server.run (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:83:8)
>     at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:40:10)
>     at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:383:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:496:3

**Comment by davidvanvo** [comment]
seeing the same

**Comment by vraicovi** [comment]
I waited two days and begrudgingly deleted the persist and cached accessory files.  It worked.
