### ISSUE TITLE
Failed to refresh devices

### ISSUE THREAD

**Issue by jalexladd** [sibartlett/homebridge-wink3#69]
After authenticating with the Wink API, I get a "failed to refresh devices" error. 

[11/23/2017, 8:32:29 PM] [Wink] Failed to refresh devices. TypeError: Cannot read property 'indexOf' of undefined
    at isOutlet (/usr/lib/node_modules/homebridge-wink3/src/devices/binary_switch.js:6:3)
    at Object.isLightBulb [as supported] (/usr/lib/node_modules/homebridge-wink3/src/devices/binary_switch.js:14:4)
    at _extends.services.definition.services.filter.service (/usr/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:30:21)
    at Array.filter (native)
    at AccessoryHelper.getDefinition (/usr/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:27:10)
    at WinkPlatform.patchAccessory (/usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:130:49)
    at WinkPlatform.getNewAccessory (/usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:167:10)
    at WinkPlatform.addDevice (/usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:173:28)
    at Array.forEach (native)
    at /usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:211:13
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/homebridge-wink3/dist/WinkPlatform.js:62:191)
    at /usr/lib/node_modules/homebridge-wink3/dist/WinkPlatform.js:62:361
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by sibartlett** [comment]
Fixed in 1.7.1
