### ISSUE TITLE
Failed to refresh devices??

### ISSUE THREAD

**Issue by emdoc12** [sibartlett/homebridge-wink3#8]
So I tried to move from homebridge-winkv3 to home bridge-wink3 and I'm running into an error now.
I'm sure its something simple but I just can't seem to figure it out. Any help would be great. 

`[5/17/2017, 2:01:35 PM] Homebridge is running on port 51826.
[5/17/2017, 2:01:36 PM] [Wink] Authenticated with wink.com
[5/17/2017, 2:01:36 PM] [Wink] Refreshing devices...
[5/17/2017, 2:01:37 PM] [Wink] Failed to refresh devices. TypeError: Cannot read property 'services' of undefined
    at AccessoryHelper.getDefinition (/usr/lib/node_modules/homebridge-wink3/src/AccessoryHelper.js:25:17)
    at WinkPlatform.patchAccessory (/usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:76:49)
    at WinkPlatform.addDevice (/usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:103:10)
    at Array.forEach (native)
    at /usr/lib/node_modules/homebridge-wink3/src/WinkPlatform.js:136:13
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/homebridge-wink3/dist/WinkPlatform.js:32:191)
    at /usr/lib/node_modules/homebridge-wink3/dist/WinkPlatform.js:32:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
[5/17/2017, 2:01:42 PM] [Wink] Wink hub (192.168.1.159) is not reachable locally { RequestError: Error: ESOCKETTIMEDOUT
    at new RequestError (/usr/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-wink3/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-wink3/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-wink3/node_modules/request/request.js:822:16)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:188:7)
  name: 'RequestError',
  message: 'Error: ESOCKETTIMEDOUT',
  cause: 
   { Error: ESOCKETTIMEDOUT
       at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-wink3/node_modules/request/request.js:819:19)
       at Object.onceWrapper (events.js:293:19)
       at emitNone (events.js:86:13)
       at ClientRequest.emit (events.js:188:7)
       at TLSSocket.emitTimeout (_http_client.js:679:10)
       at Object.onceWrapper (events.js:293:19)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:188:7)
       at TLSSocket.Socket._onTimeout (net.js:352:8)
       at ontimeout (timers.js:386:14) code: 'ESOCKETTIMEDOUT', connect: false },
  error: 
   { Error: ESOCKETTIMEDOUT
       at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-wink3/node_modules/request/request.js:819:19)
       at Object.onceWrapper (events.js:293:19)
       at emitNone (events.js:86:13)
       at ClientRequest.emit (events.js:188:7)
       at TLSSocket.emitTimeout (_http_client.js:679:10)
       at Object.onceWrapper (events.js:293:19)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:188:7)
       at TLSSocket.Socket._onTimeout (net.js:352:8)
       at ontimeout (timers.js:386:14) code: 'ESOCKETTIMEDOUT', connect: false },
  options: 
   { baseUrl: 'https://192.168.1.159:8888',
     strictSSL: false,
     json: false,
     method: 'GET',
     uri: '/',
     timeout: 5000,
     headers: { 'User-Agent': 'Manufacturer/Apple-iPhone8_1 iOS/10.3.1 WinkiOS/5.8.0.27-production-release (Scale/2.00)' },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

`

**Comment by sibartlett** [comment]
Ive publish a new version `1.1.4`, which should address this issue.

**Comment by sibartlett** [comment]
Also, I noticed that there is another log message that reads "Wink hub (192.168.1.159) is not reachable locally". It also includes a stack trace, which makes it appear like an error - however, it's just a warning. I'll probably publish another version later that amends that log entry to not include the stack trace.

**Comment by sibartlett** [comment]
By bad. I didn't properly fix the issue, now it's fixed for sure in `1.1.5`.

**Comment by sibartlett** [comment]
Sorry, I mean version `1.1.6`
