### ISSUE TITLE
select an accessory to add to home

### ISSUE THREAD

**Issue by jrcharles** [sibartlett/homebridge-wink3#83]
Hello,

I was able to get Homebridge setup on my raspberry pi, launched.

I see commands like below when I make commands in the wink app
[2018-1-8 18:22:17] [Wink] Received update notification: Kitchen Light (binary_switch/61009)

I'm stuck at getting it to work with my Home App.  I've typed in the code and it just stays  at "Select an accessory to add to Home.  I currently have no accessories in the my config file.  That is:
"accessories": [],

However, when I do add accessories such as:
"accessories": [59681,59498,61887],

I get this error: /usr/lib/node_modules/homebridge/lib/server.js:201
    config = JSON.parse(fs.readFileSync(configPath));
                  ^
SyntaxError: Unexpected token ] in JSON at position 467
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by jrcharles** [comment]
I have probably 14 or 15 z-wave binary switches that control all of our lights/fans in our house.... do I need to install a different plugin in addition to homebridge-wink3?

I also have 2 nests.... do I need to do more stuff in addition?

**Comment by jrcharles** [comment]
Any assistance would be create... I feel like I'm so close, but I'm missing something.  Any help you can give me would be great.

**Comment by rrrrrk** [comment]
Here are some things you could try

Remove the accessories [] part in your config, I don't think you need that.
In the bridge section of the config.json, try changing the username XX:XX:XX:XX:XX:XX to something different.
Change the pin to something different.
Delete your accessories and persist folder on your homebridge server.
Make sure your phone and homebridge server are on the same subnet.
Delete your Home on your phone if you have one.

Try adding it and setting it up again after that.
