### ISSUE TITLE
No Doorbell Notifications from Ring Doorbell 2

### ISSUE THREAD

**Issue by mludowise** [sibartlett/homebridge-wink3#99]
I just installed this homebridge plugin to get motion and doorbell notifications from my Ring doorbell. I'm currently getting motion notifications but not any doorbell notifications.

I saw issue #36 make reference to door bell. It looks like the associated PR was merged but the issue was never closed. Am I supposed to get any doorbell notifications for my doorbell or is it motion only?

P.S. Thanks for your hard work. This is a great plugin!

**Comment by davidvanvo** [comment]
i’ve only received motion.

**Comment by mludowise** [comment]
I saw that this is commented out in `door_bell.js`:
```
// TODO: Requires more testing	+      {
-      // {	+        service: Service.Doorbell,
-      //   service: Service.Doorbell,	+        supported: state => state.button_pressed !== undefined,
-      //   supported: state => state.button_pressed !== undefined,	+        characteristics: [
-      //   characteristics: [	+          {
-      //     {	+            characteristic: Characteristic.ProgrammableSwitchEvent,
-      //       characteristic: Characteristic.ProgrammableSwitchEvent,	+            get: state => (state.button_pressed ? 0 : null)
-      //       get: state => (state.button_pressed ? 0 : null)	+          }
-      //     }	+        ]
-      //   ]	+      },
-      // },
```

I tried to fork the repo, uncomment those lines, and do an npm install from github but ran into errors when trying to run homebridge. I'm assuming it's because the github repo is missing some files that are included on npm or something along those lines.
```
====================
[2018-7-7 13:14:13] ERROR LOADING PLUGIN homebridge-wink3:
[2018-7-7 13:14:13] Error: Cannot find module '/Users/thedoctor/.npm-global/lib/node_modules/homebridge-wink3/dist/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:148:14)
    at Array.forEach (<anonymous>:null:null)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:140:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

Anyway... if someone knows how to fix the issues with my fork or puts a beta out on NPM, I'd be happy to test it and see if it works.

**Comment by sibartlett** [comment]
@mludowise the error you're getting is due to the code needing to be compiled. I'll try and write some documentation regarding that.

It'd be great if I can have some help to implement doorbell notifications though! As I don't have a doorbell to test with.

**Comment by mludowise** [comment]
Awesome! I’ll See if I can try it out over the weekend.

**Comment by Kroellie** [comment]
Is this still an issue? I can see Wink registering my motions and doorbell presses, but nothing happens with the sensors in homekit?
